apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.0
controlPlaneEndpoint: "54.255.175.236"
networking:
  podSubnet: "10.100.0.1/24"
scheduler:
  extraArgs:
controllerManager:
  extraArgs:
    cloud-provider: aws
apiServer:
  extraArgs:
    cloud-provider: aws
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
